# Elements of linear algebra

#### Create a one-dimensional array (vector) of the first 10 natural numbers and print its values.

In [1]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10],dtype=int)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
import numpy as np
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


#### Create a 3x3 matrix of zeros and print its values.

In [1]:
import numpy as np
a = np.array([[0, 0, 0],
                      [0, 0, 0],
                      [0, 0, 0]])

print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [3]:
import numpy as np
a = np.zeros((3, 3), dtype=int)

print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### Create a 5x5 matrix of random integers between 1 and 10 and print its values.

In [4]:
import numpy as np

a = np.random.randint(1, 11, (5, 5))

print(a)

[[ 6  6  1  8  9]
 [ 8  8  2  9  3]
 [ 4  4  7  4  3]
 [ 8  8  6  5  6]
 [ 3  5 10  7  2]]


#### Create a 4x4 matrix of random real numbers between 0 and 1 and print its values.

In [7]:
import numpy as np
a = np.random.rand(4,4)
print(a)

[[0.08600624 0.84042088 0.10152292 0.62900053]
 [0.76320404 0.13465201 0.48043392 0.10066763]
 [0.62948163 0.82122857 0.63892535 0.32472204]
 [0.50306871 0.34142149 0.57745038 0.33279787]]


#### Create two 5-element vectors of random integers between 1 and 10, and perform element-wise addition, subtraction, and multiplication on them.

In [12]:
import numpy as np
one = np.random.randint(1,11,5)
print(one)
two = np.random.randint(1,11,5)
print(two)
result_add = one + two
print(result_add)
result_sub = one - two
print(result_sub)
result_mul = one * two
print(result_mul)

[10  3  7  9  6]
[ 3 10  4  8 10]
[13 13 11 17 16]
[ 7 -7  3  1 -4]
[30 30 28 72 60]


#### Create two vectors of size 7, fill them with arbitrary numbers, and find their dot product.

In [14]:
import numpy as np
one = np.random.rand(7)
print("One:", one)
two = np.random.rand(7)
print("Two:", two)
result = np.dot(one, two)
print("Result:", result)

One: [0.27204556 0.82504947 0.03306127 0.06726138 0.20616766 0.49918153
 0.30693842]
Two: [0.37586671 0.36672783 0.52543684 0.68078618 0.76787351 0.93536926
 0.76805726]
Result: 1.3289597243086204


#### Create two matrices of size 2x2 and 2x3, fill them with random integers between 1 and 10, and multiply them together.

In [18]:
import numpy as np
one = np.random.randint(1,11, (2,2))
print("One:", one)
two = np.random.randint(1,11, (2,3))
print("Two:", two)
result = np.dot(one,two)
print("Result:", result)

One: [[8 3]
 [9 9]]
Two: [[ 9  8  4]
 [10  9  2]]
Result: [[102  91  38]
 [171 153  54]]


#### Create a 3x3 matrix of random integers between 1 and 10, and find its inverse matrix.

In [20]:
import numpy as np
a = np.random.randint(1,11, (3,3))
print("Array:", a)
a_inv = np.linalg.inv(a)
print("Inverse", a_inv)

Array: [[10  7  9]
 [ 6  4  3]
 [ 7  8  1]]
Inverse [[-0.23529412  0.76470588 -0.17647059]
 [ 0.17647059 -0.62352941  0.28235294]
 [ 0.23529412 -0.36470588 -0.02352941]]


#### Create a 4x4 matrix of random real numbers between 0 and 1, and transpose it.

In [2]:
import numpy as np
a = np.random.rand(4, 4)
print("Origin:",a)
transposed_matrix = a.T
print("Transposed matrix:", transposed_matrix)

Origin: [[0.47434791 0.06822895 0.15862982 0.11320108]
 [0.87961812 0.75423703 0.45710775 0.96689508]
 [0.6406212  0.05281806 0.66471632 0.33749654]
 [0.5557493  0.38283369 0.70913081 0.81983683]]
Transposed matrix: [[0.47434791 0.87961812 0.6406212  0.5557493 ]
 [0.06822895 0.75423703 0.05281806 0.38283369]
 [0.15862982 0.45710775 0.66471632 0.70913081]
 [0.11320108 0.96689508 0.33749654 0.81983683]]


#### Create a 3x4 matrix and a vector of size 4, fill them with random integers between 1 and 10, and multiply the matrix by the vector.

In [5]:
import numpy as np
array = np.random.randint(1,11, (3,4))
print("Array:", array)
vector = np.random.randint(1, 11, 4)
print("Vector", vector)
result = np.dot(array, vector)
print("Result", result)

Array: [[ 6  4  9  5]
 [10  3  8 10]
 [ 5  2  7  4]]
Vector [6 6 7 2]
Result [133 154  99]


#### Create a 2x3 matrix and a vector of size 3, fill them with random real numbers between 0 and 1, and multiply the matrix by the vector.

In [7]:
import numpy as np
array = np.random.rand(2, 3)
print("Array:", array)
vector = np.random.rand(3)
print("Vector", vector)  
result = np.dot(array, vector)
print("Result", result)

Array: [[0.8643839  0.52571956 0.38774307]
 [0.67144436 0.42571998 0.50505276]]
Vector [0.82514026 0.81448027 0.61211195]
Result [1.37876833 1.20992512]


#### Create two 2x2 matrices, fill them with random integers between 1 and 10, and perform element-wise multiplication.

In [8]:
import numpy as np
array1 = np.random.randint(1,11, (2,2))
print("Array:", array1)
array2 = np.random.randint(1,11, (2,2))
print("Array:", array2)
result = array1 * array2
print("Result", result)

Array: [[2 7]
 [1 2]]
Array: [[6 1]
 [8 6]]
Result [[12  7]
 [ 8 12]]


#### Create two 2x2 matrices, fill them with random integers between 1 and 10, and find their product.

In [9]:
import numpy as np
array1 = np.random.randint(1,11, (2,2))
print("Array:", array1)
array2 = np.random.randint(1,11, (2,2))
print("Array:", array2)
result = np.dot(array1, array2)
print("Result:", result)

Array: [[9 2]
 [1 4]]
Array: [[8 1]
 [7 5]]
Result: [[86 19]
 [36 21]]


#### Create a 5x5 matrix, fill it with random integers between 1 and 100, and find the sum of the matrix elements.

In [11]:
import numpy as np
array1 = np.random.randint(1,101, (5,5))
print("Array:", array1)
result = array1.sum()
print("Result:", result)

Array: [[ 73  63  86  12  46]
 [ 83  26  96  64  73]
 [ 28  33  80 100  16]
 [  8 100  34  59  17]
 [ 37 100  77  60  21]]
Result: 1392


#### Create two 4x4 matrices, fill them with random integers between 1 and 10, and find their difference.

In [12]:
import numpy as np
array1 = np.random.randint(1,11, (4,4))
print("Array:", array1)
array2 = np.random.randint(1,11, (4,4))
print("Array:", array2)
result = array1 - array2
print("Result:", result)

Array: [[10  6  4  1]
 [ 2  9  7 10]
 [10 10  4  6]
 [ 5  8  6  3]]
Array: [[10  5 10  3]
 [ 5  6  5  3]
 [ 2  6  2  2]
 [ 5  7  7  6]]
Result: [[ 0  1 -6 -2]
 [-3  3  2  7]
 [ 8  4  2  4]
 [ 0  1 -1 -3]]


#### Create a 3x3 matrix, fill it with random real numbers between 0 and 1, and find the column vector containing the sum of the elements of each row of the matrix.

In [17]:
import numpy as np
array1 = np.random.rand(3, 3)
print("Array:", array1)
row_sums = np.sum(array1, axis=1)
print("Rowsum:",row_sums)
column_vector = np.reshape(row_sums, (3, 1))
print("Column vector:", column_vector)

Array: [[0.76003355 0.35129977 0.37503881]
 [0.67264582 0.45186787 0.3853841 ]
 [0.26374742 0.88963581 0.64058171]]
Rowsum: [1.48637214 1.50989779 1.79396494]
Column vector: [[1.48637214]
 [1.50989779]
 [1.79396494]]


#### Create a 3x4 matrix with arbitrary integers and create a matrix with the squares of these numbers.

In [20]:
import numpy as np
array = np.random.randint(1, 16, (3, 4))
print("Array:", array)
result = array**2
print("Result:", result)

Array: [[14  2 12  7]
 [10  5 14  5]
 [12  8 10  2]]
Result: [[196   4 144  49]
 [100  25 196  25]
 [144  64 100   4]]


#### Create a vector of size 4, fill it with random integers between 1 and 50, and find the vector with the square roots of these numbers.

In [22]:
import numpy as np
array = np.random.randint(1, 51, (4))
print("Array:", array)
result = np.sqrt(array)
print("Result:", result)

Array: [47 41 12  8]
Result: [6.8556546  6.40312424 3.46410162 2.82842712]
